iDigBio/idb-backend

setup.py

See http://initd.org/psycopg/articles/2018/02/08/psycopg-274-released/

psycopg2 package deprecated by upstream in favor of psycopg2-binary

---

.gitignore
idigbio_ingestion/update_publisher_recordset.py

This should now not be a fatal exception that stops processing an entire RSS feed:
```
Error with 5ded2005-0563-4737-9830-e951dab59c66 http://ipt.tacc.utexas.edu/rss.do
DETAIL:  Key (file_link)=(http://ipt.tacc.utexas.edu/archive.do?r=npl) already exists.
```
Now will skip items (and log ERROR) that have a recordid conflict (the same recordid appearing in two different feeds) instead of completely aborting an entire feed.  A few other cases may also be resolved.
See redmine 3124.
Other refactoring to improve maintainability.

fix various issues with recordids in publisher feeds

---

idb/helpers/fieldnames.py

fixes
```
root@c18node4:/mnt/data/new_ingestion# cat b293a647-5fb8-4b82-bf5b-571e7d6fad03.db_check.log 
2019-08-07 22:53:57.582 INFO  idb.db-check.b293a647-5fb8-4b82-bf5b-571e7d6fad03჻ Starting db_check ingest: False
2019-08-07 22:53:57.602 INFO  idb.db-check.b293a647-5fb8-4b82-bf5b-571e7d6fad03჻ Fetching etag 9f0a9ad6c1d1da14e49445c0fc43b07f to 'b293a647-5fb8-4b82-bf5b-571e7d6fad03'
2019-08-07 22:53:57.706 INFO  idb.db-check.b293a647-5fb8-4b82-bf5b-571e7d6fad03჻ Building ids/uuids json
2019-08-07 22:53:57.806 INFO  idb.db-check.b293a647-5fb8-4b82-bf5b-571e7d6fad03჻ Processing b293a647-5fb8-4b82-bf5b-571e7d6fad03, type: application/zip
2019-08-07 22:53:58.362 INFO  idb.b293a647-5fb8-4b82-bf5b-571e7d6fad03჻ Schema validation failed, continuing unvalidated
2019-08-07 22:53:58.364 DEBUG …
```

add ChronometricAge extension

---

idigbio_ingestion/cli.py
idigbio_ingestion/update_publisher_recordset.py

Add a way to manually upload a dataset file for a given recordset uuid, out-of-band with the normal RSS processing.
Needed to work around Naturalis API issues (unable to retrieve the entire archive most of the time).

Manual dataset upload to work 

---

idb/helpers/storage.py

update publisher service logs were getting spammed with
`Initialized IDigBioStorage connection (boto.connect_s3) to host...`

reduce loglevel of initialized statement

---

idb/postgres_backend/gevent_helpers.py

fixes #60 
db connect error etc. will cause exception to be raised, fatal and kill the service.

catch other exceptions such as when db is missing

---

README.md

Ubuntu Trusty (14.04) is EOL as of 2019-04-30.
Closes #75

remove installation instructions for Ubuntu 14.04

---

docker-compose.yml

Originally I thought tacklebox would be better to start "if needed"
from the host.
However, this makes it a little less usable since one has to first
locate the proper docker network and start tacklebox on that
particular network.
For now, letting docker-compose start tacklebox so it is already on
the same network.
The containers on the same docker network can all reach each other
by their short names thanks to docker networking.
dev-database
dev-storage
dev-elasticsearch

docker-compose container naming and improve tacklebox startup loglines

---

README.md

It is needed by test suite:
tests/idigbio_ingestion/mediaing/test_derivatives.py

add libfreetype6-dev to package requirements

---

setup.py

Fixes #92 
* install pillow-simd only on specific older python versions
* abort the install if on Python 3

add python version-specific behaviors to setup.py

---

README.md
requirements.txt
setup.py

The PyPi package `systemd-python` cannot handle our unicode characters in dataset names such as:
'ZUEC-HEM - Coleção de Hemiptera do Museu de Zoologia da UNICAMP - Version 1.48'
We get errors such as:
```
Aug 17 20:48:21 c18node4 idigbio-ingestion[22407]: UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 144: ordinal not in range(128)
Aug 17 20:48:21 c18node4 idigbio-ingestion[22407]: Logged from file update_publisher_recordset.py, line 311
Aug 17 20:48:21 c18node4 idigbio-ingestion[22407]: Traceback (most recent call last):
Aug 17 20:48:21 c18node4 idigbio-ingestion[22407]:   File "/usr/local/lib/python2.7/dist-packages/systemd/journal.py", line 602, in emit
Aug 17 20:48:21 c18node4 idigbio-ingestion[22407]:     **extras)
Aug 17 20:48:21 c18node4 …
```

use python-systemd Ubuntu package instead of systemd-python pip package

---

idb/config.py
idb/indexing/__init__.py
idb/indexing/index_from_postgres.py
idb/indexing/indexer.py

Create the index if it does not exist and specify the settings appropriate for the cluster (shard count and replicas).
- Create index requires an additional environment variable to be set: `ES_ALLOW_INDEX_CREATION=yes`
- Moved a number of items into `config` object.
- Add some loglines.
- If ENV is `dev` do not try to connect to remote Elasticsearch cluster (use `localhost`).
Closes #98 
Closes #70 
Sample:
```
idb -v --logfile ./index-test-creates.log index --indexname dan-test-creates-index --no-index full
20:00:59.063 INFO  idb.indexing჻ Enabling no-index dry run mode
20:00:59.065 INFO  idb.indexer჻ Initializing ElasticSearchIndexer(u'dan-test-creates-index', [u'publishers', u'recordsets', u'mediarecords', u'records'], First cluster node: u'c20node1.acis.ufl.edu:9200')
20:00:59.075 …
```

create the index if it does not exist

---

idb/indexing/indexer.py

Apparently not supported here:
TypeError: bulk() got an unexpected keyword argument 'max_retries'

remove unsupported param

---

idigbio_ingestion/db_check.py

* log more context of the row causing the `RecordException`
* purge large amounts of commented-out code and other comment fixups
* leverage IDB_EXTRA_SERIOUS_DEBUG

log more context of the row causing the exception

---

idigbio_ingestion/lib/delimited.py

In meta.xml, `encoding=""` is not valid and should be caught immediately.

Catch empty string encoding

---

idb/helpers/fieldnames.py

See: https://tdwg.github.io/chrono/list/
In iDigBio, the UF Environmental Archaeology (zooarch) datasets are
trying to use this now instead of zooarchnet.

ChronometricAge is now a darwin core extension

---

setup.py

Latest (1.4.x) pyquery breaks in python 2 because it is using incompatible import:
```
from urllib.parse import urlencode
E   ImportError: No module named parse
```
Pin the pyquery version to one known to work in python 2.

pin version of pyquery since newest lib is incompatible with py2

---

setup.py

It seems that specifying 'pyquery==1.2' was not
getting the latest patch version under 1.2.  pip was installing
literal 1.2 version.
We need at least 1.2.7 for a particular `.text()` behavior, and
1.2.17 is the latest and known to work.
We still cannot move the the next minor version afaik.

pin pyquery to latest compatible minor version

---

idigbio_ingestion/lib/dwca.py

etree.parse(URL) does not support https locations.
It does require a file-like object.
Download the schema using requests, turn the content
into a file-like object, then try to parse it into a usable
schema.

download xml schema before trying to parse it

---

etc/systemd/system/idigbio-ingestion-derivatives.timer
idigbio_ingestion/mediaing/derivatives.py

* modify systemd timer to shorten delay between derivative runs
* `size` is a named parameter.  The cli option `--procs` now properly gets used through when creating the Pool
Fixes #142

Derivatives multiprocessing procs fix, tweak timer

---

idigbio_ingestion/lib/dwca.py

readline in dwca.py is un-used, I think.
dwca.py is concerned with the archive file itself.
The reading of the constituent files happens in delimited.py which
has its own readline function defined.

remove un-used readline function

---

idb/indexing/index_helper.py

Elasticsearch does not allow field names containing dots.
Sample record:
```json
{
"dwc:organismQuantity" : "1",
"dwc:institutionCode" : "RBINS-Scientific Heritage",
"dwc:scientificNameAuthorship" : "Stechow, 1919",
"dwc:datasetID" : "be_rbins_darwin",
"dcterms:rightsHolder" : "Royal Belgian Institute of Natural Sciences",
"dwc:basisOfRecord" : "PreservedSpecimen",
"dwc:genus" : "Plumularia Lamarck",
"dcterms:type" : "PhysicalObject",
"dwc:otherCatalogNumbers" : "urn:catalog:RBINS:IG:27838",
"dwc:family" : "Plumulariidae",
"dwc:collectionCode" : "urn:catalog:RBINS:hyd",
"dwc:verbatimLocality" : "Seychelles",
"dwc:taxonomicStatus" : "valid",
"dcterms:license" : "https://creativecommons.org/licenses/by-nc/4.0",
"obis:ExtendedMeasurementOrFact" : [
{
"coreid" : …
```

truncate problematic objects containing dots in fieldnames

---

README.md
etc/systemd/system/idigbio-ingestion-derivatives.service
etc/systemd/system/idigbio-ingestion-mediaing-get-media.service
etc/systemd/system/idigbio-ingestion-mediaing-migrate.service
etc/systemd/system/idigbio-ingestion-mediaing-updatedb.service
etc/systemd/system/idigbio-ingestion-update-publisher-recordset.service

Update docs and systemd unit files to enable services on the new workflow node with a non-root user.
Point the backend at the s2 blob storage gateways to avoid impacting user-facing storage gateways.

change systemd units to work with non-root user

---

README.md

I'm not sure how Nathan did this on the previous workflow node for the root user, but making symlinks into the virtual env seems to work.

update README with howto get idb binaries in path

---

idb/indexing/index_from_postgres.py

Now that we have stopped fatal abort on every indexing exception, we need to log the errors that actually occur.
This is working beautifully now.
Sample logline:
```
2021-11-13 12:24:17.042 WARNI idb.index_from_postgres჻ Failed during bulk index index: {u'index': {u'status': 400, u'_type': u'records', u'_id': u'026de0a3-def4-4d08-9db8-d6638ab8e8d3', u'error': {u'reason': u"Field name [https://symbiota.org/terms/recordEnteredBy] cannot contain '.'", u'type': u'mapper_parsing_exception'}, u'_index': u'idigbio-dan-test-1'}} 
```

log errors during bulk indexing

---

setup.py

On some systems, pip gives the following when trying to install requirements:
ERROR: pip's legacy dependency resolver does not consider dependency conflicts
when selecting packages. This behaviour is the source of the following dependency
conflicts.
requests 2.20.0 requires chardet<3.1.0,>=3.0.2, but you'll have chardet 4.0.0 which is incompatible.
pin chardet to the version known to work in production: 3.0.4.

pin `chardet` version

---

idb/helpers/fieldnames.py
idigbio_ingestion/db_check.py
idigbio_ingestion/lib/dwca.py

Support new term sources in data published by ALA.
Trigger fatal error when dotted fieldnames are detected
While processing darwin core archives, we normally map dotted term
references to a CURIE.
"http://rs.tdwg.org/dwc/terms/occurrenceID" as specified in meta.xml
becomes "dwc:dwc:occurrenceID" when we store the field in postgres.
In situations where new terms are introduced by the community from
previously-unknown namespaces, the code was previously defaulting
to using the field-name as-provided (including the dots "."). This
had downstream effects during Indexing because Elasticsearch no
longer supports dots in fieldnames.
The code changes here will prevent field names with dots from
being created in the database and should prevent the negative
downstream effect during indexing.

ALA new namespaces

---

README.md

INFO will cause Celery to output items such as:
```
[2022-03-08 20:37:33,106: INFO/MainProcess] Connected to redis://redis.host.example.com:6379/1
[2022-03-08 20:37:33,116: INFO/MainProcess] mingle: searching for neighbors
[2022-03-08 20:37:34,175: INFO/MainProcess] mingle: sync with 4 nodes
```

suggest INFO for celery logging level

---

idigbio_workers/__init__.py

Figured out how to test (`celery worker ...`).  
After further iteration I was still unable to get a code change that actually got additional loglines into the Celery logging output.
Seems better to revert iDigBio/idb-backend#207
Running with `celery worker --app=idigbio_workers -l INFO` will include the desired info in Celery's output.

Revert "add logging when worker connects to redis"

---

idb/indexing/__init__.py
idb/indexing/index_from_postgres.py

```
idb index mappings --help
Usage: idb index mappings [OPTIONS]
PUT mappings only and then exit
```

add "mappings" command to idb index to only put mappings

---

.devcontainer/.dockerignore
.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.devcontainer/docker-compose-base.yml
.devcontainer/requirements.txt

These changes made the VS Code "open in container" feature work for me.  Rather than reference the container development Dockerfile (i.e. the one inside .devcontainer) directly in .devcontainer.json, a new docker-compose-base.yml file is referenced which mounts the project directory.  The old docker-compose file, which has services for Postgres and MinIO for running the tests, is unchanged.  This is working for me with VS Code on Ubuntu 22 and on an M1 Macbook.
The Dockerfile also has changes: it starts from the python:2.7 image rather than the idigbio image.  This change is left over from experimenting with Py4J and I am not sure it is required to make the "open in container" feature work.

Updating .devcontainer for VS Code Docker development

---

.travis.yml

The highest version to which I could update was postgres 12 on Ubuntu 'focal'.
Travis does not support adding arbitrary 3rd party repos. Travis does not support python 3.8.10 on Ubuntu 22.04 'jammy'.
I ran into job timeout issues, docker build is not compatible with travis_wait.

update travis pipeline to use pg 12

---

idb/helpers/conversions.py

As reported in https://github.com/iDigBio/idb-backend/issues/229 the oldest natural history records actually date back to the 1500s rather than 1700.
I have confirmed there are some digitized records in GBIF from the 1600s.
Moving our zero date back a few hundred years.

allow dates back to the 1500s

---

idb/corrections/gbif_record_corrector.py
idb/indexing/__init__.py
setup.py

I've updated setup.py to import the Python-side Py4J library, added a "--gbif" flag option to the indexing command, and included a Python class in idb/corrections/gbif_record_corrector.py to serve as a stub for doing Java record correction.  If a Py4J gateway server is not running on the indexing host, it will error out with a message and a stack trace.  Indexing will default to the normal idb-backend record correction.

Setting up Py4J record correction option in indexing

---

idigbio_ingestion/mediaing/fetcher.py

Fetcher seems to be stuck behind a bunch of retries.
Reduce the automated retries to get that work out of the way.  The longer-term retry process (currently 30 days) will come back again and retry those again.

decrease the number of fetcher media retries

---

idigbio_ingestion/mediaing/__init__.py

This prevents fetching from the Arctos domain for mediang when it is run.

restrict arctos domain
